apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thumbor
  template:
    metadata:
      labels:
        app: thumbor
    spec:
      containers:
      - name: thumbor
        image: dlscloud/thumbor-app:v1
        ports:
        - containerPort: 8888
        env:
          - name: EP_URL
            valueFrom:
              secretKeyRef:
                name: thumbor-secrets
                key: ep_url
          - name: KEY_ID
            valueFrom:
              secretKeyRef:
                name: thumbor-secrets
                key: key_id
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: thumbor-secrets
                key: access_key
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: thumbor-secrets
                key: bucket_name
        volumeMounts:
        - name: thumbor-storage
          mountPath: "/data"
        imagePullPolicy: Always
      volumes:
      - name: thumbor-storage
        persistentVolumeClaim:
          claimName: thumbor-pvc
