on:
  workflow_call:
    inputs:
      working-dir:
        type: string
        description: The path to one of the python packages
        required: true
      python-version:
        type: string
        description: The version of python to install
        required: true
    secrets:
      CODECOV_TOKEN:
        required: true

env:
  # https://github.com/pytest-dev/pytest/issues/2042
  PY_IGNORE_IMPORTMISMATCH: "1"

jobs:
  run:
    runs-on: iris-cpu
    container: catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - if: inputs.python-version == 'dev'
        name: Install dev versions of python packages
        uses: ./.github/actions/install_requirements
        with: 
          working-dir: ${{ inputs.working-dir }}

      - if: inputs.python-version == 'dev'
        name: Write the requirements as an artifact
        working-directory: ${{ inputs.working-dir }}
        run: pip freeze --exclude-editable > /tmp/dev-requirements.txt

      - if: inputs.python-version == 'dev'
        name: Upload dev-requirements.txt
        uses: actions/upload-artifact@v4
        with:
          name: dev-requirements-${{ inputs.working-dir }}
          path: /tmp/dev-requirements.txt

      - if: inputs.python-version != 'dev'
        name: Install latest versions of python packages
        uses: ./.github/actions/install_requirements
        with:
          working-dir: ${{ inputs.working-dir }}
          python-version: ${{ inputs.python-version }}
          pip-install: ".[dev]"

      - name: Run tests
        working-directory: ${{ inputs.working-dir }}
        run: tox -e tests

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     name: ${{ inputs.python-version }}/${{ inputs.runs-on }}
      #     files: cov.xml
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
